global:
    scrape_interval: 5s

scrape_configs:
    - job_name: 'gateway'
      metrics_path: '/metrics'
      static_configs:
          - targets:
                - 'gateway-service:4000'

    - job_name: 'auth'
      metrics_path: '/metrics'
      static_configs:
          - targets:
                - 'auth-service:9101'

    - job_name: 'notification'
      metrics_path: '/metrics'
      static_configs:
          - targets:
                - 'notification-service:9102'

    - job_name: 'postgres'
      static_configs:
          - targets:
                - 'postgres-exporter:9187'

    - job_name: 'redis'
      static_configs:
          - targets:
                - 'redis-exporter:9121'

    - job_name: 'rabbitmq'
      static_configs:
          - targets:
                - 'rabbitmq-exporter:9419'

    - job_name: 'node'
      static_configs:
          - targets:
                - 'node-exporter:9100'

    - job_name: 'prometheus'
      static_configs:
          - targets:
                - 'prometheus:9090'
